# Configuração dos motores de busca
engines:
  - name: google
    engine: google
    shortcut: go
    disabled: false

  - name: yahoo
    engine: yahoo
    shortcut: yh
    disabled: false

  - name: bing
    engine: bing
    shortcut: bi
    disabled: false

  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
    disabled: false

  - name: brave
    engine: brave
    shortcut: br
    disabled: false

  # Motores de busca para produtos
  - name: buscape
    engine: xpath
    search_url: https://www.buscape.com.br/search?q={query}
    title_xpath: //h2/a
    url_xpath: //h2/a/@href
    content_xpath: //p[@class='snippet']
    disabled: false

  - name: zoom
    engine: xpath
    search_url: https://www.zoom.com.br/search?q={query}
    title_xpath: //h2/a
    url_xpath: //h2/a/@href
    content_xpath: //p[@class='snippet']
    disabled: false

# Configurações gerais de busca
search:
  safe_search: 1  # SafeSearch: 0: Desligado, 1: Moderado, 2: Estrito
  method: "POST"  # Usar método POST para consultas
  default_lang: "pt-BR"  # Idioma padrão: Português Brasil
  max_page: 0  # Número de páginas ilimitado

# Configurações para resultados JSON (extração de dados como preço, marca, ean, modelo)
engines:
  - name: google_cse
    engine: google_custom
    shortcut: gcs
    api_key: 'AIzaSyB3qUC8PVvrkzOfEaf4Xip1ZKnF7sUNWgA'
    cx: '1717f12744a804305'
    search_url: "https://www.googleapis.com/customsearch/v1?q={query}&key={api_key}&cx={cx}"
    paging: true
    timeout: 10.0
    categories: [general]
    disabled: false

# Configurações gerais
general:
  debug: false
  instance_name: "SearXNG"
  privacypolicy_url: false
  donation_url: false
  contact_url: false
  enable_metrics: true
  legal_name: ""
  legal_url:

brand:
  new_issue_url: https://github.com/searxng/searxng/issues/new
  docs_url: https://docs.searxng.org/
  public_instances: https://searx.space
  wiki_url: https://github.com/searxng/searxng/wiki
  issue_url: https://github.com/searxng/searxng/issues
  website_name: ""
  website_url:
  donate_url:

# Ajuste de idioma e autocomplete
search:
  safe_search: 0
  autocomplete: "google"
  autocomplete_min: 4
  default_lang: "pt-BR"
  ban_time_on_fail: 5
  max_ban_time_on_fail: 120
  suspended_times:
    SearxEngineAccessDenied: 86400
    SearxEngineCaptcha: 86400
    SearxEngineTooManyRequests: 3600
    cf_SearxEngineCaptcha: 1296000
    cf_SearxEngineAccessDenied: 86400
    recaptcha_SearxEngineCaptcha: 604800
  formats:
    - html
    - json

server:
  port: 8888
  bind_address: "127.0.0.1"
  base_url: false  # "http://example.com/location"
  limiter: false
  public_instance: false
  secret_key: "tOG1M2{7tTil3f4L"
  image_proxy: false
  http_protocol_version: "1.0"
  method: "POST"
  default_http_headers:
    X-Content-Type-Options: nosniff
    X-Download-Options: noopen
    X-Robots-Tag: noindex, nofollow
    Referrer-Policy: no-referrer

redis:
  url: false

# Configurações de interface
ui:
  static_path: ""
  static_use_hash: false
  templates_path: ""
  query_in_title: false
  infinite_scroll: true  # Ativa o scroll infinito conforme solicitado
  default_theme: simple  # Define o tema como Simple
  center_alignment: true  # Centraliza os resultados
  default_locale: "pt-BR"  # Define o idioma da interface como pt-BR
  theme_args:
    simple_style: auto  # Ajusta o estilo do tema para automático (auto)
  search_on_category_select: true  # Faz a busca automaticamente se uma categoria estiver selecionada
  hotkeys: default

# Configurações de privacidade
search:
  safe_search: 0  # SafeSearch desativado
  method: "POST"  # Consultas feitas via método POST
  autocomplete: "google"  # Utiliza o autocompletar do Google
  autocomplete_min: 4  # Número mínimo de caracteres para ativar o autocompletar
  formats:
    - html
    - json
  max_page: 0  # Número de páginas ilimitado para resultados

# Configurações de privacidade adicionais
# Modo de exibição de título da consulta e remoção de trackers da URL
query_in_title: false  # Evita que a consulta apareça no título da aba
image_proxy: false  # Proxy de imagem desativado
remove_trackers: true  # Remove rastreadores das URLs recebidas
