general:
  debug: false
  instance_name: "SearXNG"
  
search:
  safe_search: 2
  default_engine: 'google'
  autocomplete: 'google'
  engines:
    - google
    - bing

query_filters:
  google:
    site: "www.zoom.com.br OR www.buscape.com.br"
    
doi_resolvers:
  - https://doi.org/

server:
  secret_key: "iEd2t<ioq5"
  limiter: false
  image_proxy: true
  
ui:
  static_use_hash: true
