# Configuração dos motores de busca
engines:
  - name: google
    engine: google
    shortcut: go
    description_xpath: "//div[contains(@class, 'VwiC3b yXK7lf lVm3ye r025kc hJNv6b Hdw6tb')]"
    price_xpath: "//span[contains(@class, 'LI0TWe wHYlTd')]"
    rating_xpath: "//span[contains(@class, 'yi40Hd YrbPuc')]"
    image_xpath: "//meta[@property='og:image']/@content | //link[@rel='icon']/@href"
    thumbnail_xpath: "//meta[@property='og:image']/@content | //link[@rel='icon']/@href | //img/@src"
    disabled: false
    max_page: 10

  - name: yahoo
    engine: yahoo
    shortcut: yh
    rating_xpath: "//label[contains(@class, 'fw-b')]"
    image_xpath: "//meta[@property='og:image']/@content | //link[@rel='icon']/@href"
    thumbnail_xpath: "//meta[@property='og:image']/@content | //link[@rel='icon']/@href | //img/@src"
    disabled: false
    max_page: 10

  - name: bing
    engine: bing
    shortcut: bi
    image_xpath: "//meta[@property='og:image']/@content | //link[@rel='icon']/@href"
    thumbnail_xpath: "//meta[@property='og:image']/@content | //link[@rel='icon']/@href | //img/@src"
    rating_xpath: "//div[contains(@class, 'b_sritem') and contains(@class, 'b_srtxtstarcolor')]/text()"
    disabled: false
    max_page: 10

  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
    image_xpath: "//meta[@property='og:image']/@content | //link[@rel='icon']/@href"
    thumbnail_xpath: "//meta[@property='og:image']/@content | //link[@rel='icon']/@href | //img/@src"
    disabled: false
    max_page: 10

  - name: brave
    engine: brave
    shortcut: br
    price_xpath: "//div[contains(@class, 'attributes svelte-sxbzkg')]//div[contains(@class, 'r-attr text-sm')]/strong[text()='Preço']/following-sibling::text()"
    image_xpath: "//meta[@property='og:image']/@content | //link[@rel='icon']/@href"
    thumbnail_xpath: "//meta[@property='og:image']/@content | //link[@rel='icon']/@href | //img/@src"
    disabled: false
    max_page: 10

  # # Motores de busca para produtos
  # - name: buscape
  #   shortcut: bcp
  #   engine: xpath
  #   search_url: https://www.buscape.com.br/search?q={query}
  #   title_xpath: "//h2[@data-testid='product-card::name'] | //h2[contains(@class, 'ProductCard_ProductCard_Name')]"
  #   url_xpath: "//a[@data-testid='product-card::card']/@href | //a[contains(@class, 'ProductCard_ProductCard_Inner')]/@href"
  #   price_xpath: "//p[@data-testid='product-card::price'] | //p[contains(@class, 'ProductCard_ProductCard_Price')]"
  #   description_xpath: "//div[@data-testid='product-card::description'] | //div[contains(@class, 'ProductCard_ProductCard_Description')]"
  #   image_xpath: "//div[@data-testid='product-card::image']//img/@src | //div[contains(@class, 'ProductCard_ProductCard_Image')]//img/@src"
  #   thumbnail_xpath: "//div[@data-testid='product-card::image']//img/@src | //div[contains(@class, 'ProductCard_ProductCard_Image')]//img/@src"
  #   brand_model_xpath: "//h2[@data-testid='product-card::name'] | //h2[contains(@class, 'ProductCard_ProductCard_Name')]"
  #   installment_xpath: "//span[@data-testid='product-card::installment'] | //span[contains(@class, 'ProductCard_ProductCard_Installment')]"
  #   cashback_xpath: "//span[@data-testid='product-card::cashback'] | //span[contains(@class, 'ProductCard_ProductCard_CashbackInfo')]"
  #   snippet_xpath: "//div[@data-testid='product-card::description'] | //div[contains(@class, 'ProductCard_ProductCard_Description')]"
  #   content_xpath: "//div[@data-testid='product-card::description'] | //div[contains(@class, 'ProductCard_ProductCard_Description')]"
  #   rating_xpath: ".//div[@data-testid='product-card::rating']/text()"
  #   merchant_xpath: ".//div[@data-testid='product-card::description']//h3[contains(@class, 'ProductCard_ProductCard_BestMerchant__JQo_V')]/text()"
  #   disabled: false

  # - name: zoom
  #   shortcut: zm
  #   engine: xpath
  #   search_url: https://www.zoom.com.br/search?q={query}
  #   title_xpath: "//h2[@data-testid='product-card::name'] | //h2[contains(@class, 'ProductCard_ProductCard_Name')]"
  #   url_xpath: "//a[@data-testid='product-card::card']/@href | //a[contains(@class, 'ProductCard_ProductCard_Inner')]/@href"
  #   price_xpath: "//p[@data-testid='product-card::price'] | //p[contains(@class, 'ProductCard_ProductCard_Price')]"
  #   description_xpath: "//div[@data-testid='product-card::description'] | //div[contains(@class, 'ProductCard_ProductCard_Description')]"
  #   image_xpath: "//div[@data-testid='product-card::image']//img/@src | //div[contains(@class, 'ProductCard_ProductCard_Image')]//img/@src"
  #   thumbnail_xpath: "//meta[@property='og:image']/@content | //link[@rel='icon']/@href | //img/@src | //div[@data-testid='product-card::image']//img/@src | //div[contains(@class, 'ProductCard_ProductCard_Image')]//img/@src"
  #   brand_model_xpath: "//h2[@data-testid='product-card::name'] | //h2[contains(@class, 'ProductCard_ProductCard_Name')]"
  #   installment_xpath: "//span[@data-testid='product-card::installment'] | //span[contains(@class, 'ProductCard_ProductCard_Installment')]"
  #   cashback_xpath: "//span[@data-testid='product-card::cashback'] | //span[contains(@class, 'ProductCard_ProductCard_CashbackInfo')]"
  #   snippet_xpath: "//div[@data-testid='product-card::description'] | //div[contains(@class, 'ProductCard_ProductCard_Description')]"
  #   content_xpath: "//div[@data-testid='product-card::description'] | //div[contains(@class, 'ProductCard_ProductCard_Description')]"
  #   rating_xpath: ".//div[@data-testid='product-card::rating']/text()"
  #   merchant_xpath: ".//div[@data-testid='product-card::description']//h3[contains(@class, 'ProductCard_ProductCard_BestMerchant__JQo_V')]/text()"
  #   disabled: false

   # Motor do Buscapé
  - name: buscape
    engine: buscape
    shortcut: bcp
    categories: ['general', 'web']
    paging: true
    timeout: 35.0
    disabled: false
    max_page: 10

  # Motor do Zoom
  - name: zoom
    engine: zoom
    shortcut: zm
    categories: ['general', 'web']
    paging: true
    timeout: 35.0
    disabled: false
    max_page: 10
    
  - name: googlecse
    engine: google
    shortcut: gcs
    api_key: 'AIzaSyB3qUC8PVvrkzOfEaf4Xip1ZKnF7sUNWgA'
    cx: '1717f12744a804305'
    search_url: "https://www.googleapis.com/customsearch/v1?q={query}&key={api_key}&cx={cx}"
    paging: true
    timeout: 10.0
    categories: [general]
    results_query: "items"  # Para acessar a lista de resultados de pesquisa
    url_query: "link"  # O campo 'link' contém a URL do resultado
    title_query: "title"  # O campo 'title' contém o título do resultado
    content_query: "snippet"  # O campo 'snippet' contém um resumo do conteúdo
    thumbnail_query: "pagemap.cse_thumbnail[0].src"  # Extração de uma miniatura, se disponível
    image_query: "pagemap.cse_image[0].src"
    disabled: false
    thumbnail_xpath: "//meta[@property='og:image']/@content | //link[@rel='icon']/@href | //img/@src"
    max_page: 10
    
# Configurações gerais de busca
search:
  safe_search: 1  # SafeSearch: 0: Desligado, 1: Moderado, 2: Estrito
  method: "POST"  # Usar método POST para consultas
  default_lang: "pt-BR"  # Idioma padrão: Português Brasil
  max_page: 10
  

# Configurações gerais
general:
  debug: false
  instance_name: "MT Search"
  privacypolicy_url: false
  donation_url: false
  contact_url: false
  enable_metrics: true
  legal_name: ""
  legal_url:

brand:
  new_issue_url: https://github.com/searxng/searxng/issues/new
  docs_url: https://docs.searxng.org/
  public_instances: https://searx.space
  wiki_url: https://github.com/searxng/searxng/wiki
  issue_url: https://github.com/searxng/searxng/issues
  website_name: ""
  website_url:
  donate_url:

# Ajuste de idioma e autocomplete
search:
  safe_search: 0
  autocomplete: "google"
  autocomplete_min: 4
  default_lang: "pt-BR"
  ban_time_on_fail: 10
  max_ban_time_on_fail: 300
  suspended_times:
    SearxEngineAccessDenied: 600
    SearxEngineCaptcha: 600
    SearxEngineTooManyRequests: 600
    cf_SearxEngineCaptcha: 600
    cf_SearxEngineAccessDenied: 600
    recaptcha_SearxEngineCaptcha: 600
  formats:
    - html
    - json
  max_page: 0  # Número de páginas ilimitado para resultados
  paging: true

server:
  port: 8888
  bind_address: "127.0.0.1"
  base_url: false  # "http://example.com/location"
  limiter: false
  public_instance: false
  secret_key: "tOG1M2{7tTil3f4L"
  image_proxy: false
  http_protocol_version: "1.0"
  method: "POST"
  default_http_headers:
    X-Content-Type-Options: nosniff
    X-Download-Options: noopen
    X-Robots-Tag: noindex, nofollow
    Referrer-Policy: no-referrer

redis:
  url: false

# Configurações de interface
ui:
  static_path: ""
  static_use_hash: false
  templates_path: ""
  query_in_title: true
  infinite_scroll: true
  default_theme: simple
  center_alignment: true
  default_locale: "pt-BR"
  theme_args:
    simple_style: auto
  search_on_category_select: true
  hotkeys: default

# Configurações de privacidade adicionais
# Modo de exibição de título da consulta e remoção de trackers da URL
image_proxy: false  # Proxy de imagem desativado
remove_trackers: true  # Remove rastreadores das URLs recebidas
doi_resolvers:
  oadoi.org: 'https://oadoi.org/'
  doi.org: 'https://doi.org/'
  doai.io: 'https://dissem.in/'
  sci-hub.se: 'https://sci-hub.se/'
  sci-hub.st: 'https://sci-hub.st/'
  sci-hub.ru: 'https://sci-hub.ru/'

default_doi_resolver: 'oadoi.org'
outgoing:
  useragent_suffix: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36"
  request_timeout: 40.0
  # the maximum timeout in seconds
  max_request_timeout: 100.0
  # suffix of searx_useragent, could contain information like an email address
  # to the administrator
  # The maximum number of concurrent connections that may be established.
  pool_connections: 200
  # Allow the connection pool to maintain keep-alive connections below this
  # point.
  pool_maxsize: 100
  # See https://www.python-httpx.org/http2/
  enable_http2: true
  retries: 5
